import React, { useEffect, useState } from 'react';
import { AlertTriangle, Plus, RefreshCw, ShieldCheck } from 'lucide-react';

interface Props { headers: Record<string, string>; contracts: { id: string; title: string }[]; }
interface Guarantee { id: string; contract_id: string; guarantee_type: string; direction: string; amount: number; currency: string; issuer: string; beneficiary: string; serial_number: string; valid_from: string; expires_on: string; state: string; warning?: string; }

export default function GuaranteesTab({ headers, contracts }: Props) {
  const [items, setItems] = useState<Guarantee[]>([]); const [warnings, setWarnings] = useState<Guarantee[]>([]); const [open, setOpen] = useState(false); const [msg, setMsg] = useState(''); const [error, setError] = useState('');
  const [form, setForm] = useState({ contract_id: '', guarantee_type: 'performance', direction: 'RECEIVED', amount: '', currency: 'IRR', issuer: '', beneficiary: '', serial_number: '', valid_from: '', expires_on: '' });
  const api = async (path: string, opts: RequestInit = {}) => { const res = await fetch(path, { ...opts, headers }); const data = await res.json(); if (!data.success) throw new Error(data.error?.message || 'Request failed'); return data.data; };
  const load = async () => { try { const all = await Promise.all(contracts.map(c => api(`/api/v1/contracts/${c.id}/guarantees`))); setItems(all.flatMap(x => x.items || [])); setWarnings((await api('/api/v1/contracts/guarantees/warnings?days=30')).items || []); } catch (e: any) { setError(e.message); } };
  useEffect(() => { load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [contracts.length]);
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { await api(`/api/v1/contracts/${form.contract_id}/guarantees`, { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, amount: Number(form.amount) }) }); setMsg('Guarantee registered'); setOpen(false); await load(); } catch (e: any) { setError(e.message); } };
  const title = (id: string) => contracts.find(c => c.id === id)?.title || id.slice(0, 8);
  const field = (key: keyof typeof form, label: string, type = 'text') => <label style={{ fontSize: '12px', fontWeight: 600, color: '#475569' }}>{label}<input type={type} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} required style={{ display: 'block', width: '100%', boxSizing: 'border-box', marginTop: '4px', padding: '8px', border: '1px solid #cbd5e1', borderRadius: '6px' }} /></label>;
  return <div><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '18px' }}><div><h2 style={{ fontSize: '18px', margin: 0 }}>Guarantee Register</h2><p style={{ color: '#64748b', fontSize: '13px' }}>Monitor received guarantees and issued-guarantee release dates.</p></div><div style={{ display: 'flex', gap: '8px' }}><button onClick={() => load()} style={btn}><RefreshCw size={14} /> Refresh</button><button onClick={() => setOpen(!open)} style={{ ...btn, background: '#7c3aed', color: '#fff' }}><Plus size={14} /> Register guarantee</button></div></div>
    {error && <div style={banner('#fee2e2', '#991b1b')}>{error}</div>}{msg && <div style={banner('#dcfce7', '#166534')}>{msg}</div>}
    {warnings.length > 0 && <div style={banner('#fef3c7', '#92400e')}><AlertTriangle size={17} /><div><strong>{warnings.length} guarantee warning(s)</strong><div style={{ fontSize: '12px' }}>{warnings.map(w => `${title(w.contract_id)}: ${w.warning} (${w.expires_on})`).join(' · ')}</div></div></div>}
    {open && <form onSubmit={create} style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px', background: '#f8fafc', padding: '16px', borderRadius: '10px', marginBottom: '20px' }}>{field('serial_number', 'Serial number')} {field('issuer', 'Issuer')} {field('beneficiary', 'Beneficiary')} {field('amount', 'Amount', 'number')} {field('currency', 'Currency')} {field('valid_from', 'Valid from', 'date')} {field('expires_on', 'Expires on', 'date')}<label style={lab}>Contract<select value={form.contract_id} onChange={e => setForm({ ...form, contract_id: e.target.value })} required style={select}><option value="">Select contract</option>{contracts.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label style={lab}>Type<select value={form.guarantee_type} onChange={e => setForm({ ...form, guarantee_type: e.target.value })} style={select}><option>bid-bond</option><option>advance-payment</option><option>performance</option><option>insurance</option></select></label><label style={lab}>Direction<select value={form.direction} onChange={e => setForm({ ...form, direction: e.target.value })} style={select}><option>RECEIVED</option><option>ISSUED</option></select></label><button type="submit" style={{ ...btn, background: '#7c3aed', color: '#fff' }}>Save guarantee</button></form>}
    <div style={{ background: '#fff', border: '1px solid #e2e8f0', borderRadius: '10px', overflow: 'auto' }}><table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}><thead><tr>{['Contract', 'Type', 'Direction', 'Amount', 'Issuer', 'Expires', 'Status'].map(h => <th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{items.map(item => <tr key={item.id}><td style={td}>{title(item.contract_id)}</td><td style={td}>{item.guarantee_type}</td><td style={td}>{item.direction}</td><td style={td}>{item.amount.toLocaleString()} {item.currency}</td><td style={td}>{item.issuer}</td><td style={td}>{item.expires_on}</td><td style={td}><span style={{ color: item.warning ? '#b45309' : '#166534', fontWeight: 700 }}>{item.warning || item.state}</span></td></tr>)}</tbody></table>{items.length === 0 && <div style={{ padding: '30px', textAlign: 'center', color: '#94a3b8' }}>No guarantees registered.</div>}</div>
    <div style={{ marginTop: '18px', color: '#64748b', fontSize: '12px' }}><ShieldCheck size={14} style={{ verticalAlign: 'middle' }} /> Warning data is refreshed whenever this dashboard opens or refreshes.</div>
  </div>;
}
const btn: React.CSSProperties = { display: 'inline-flex', gap: '6px', alignItems: 'center', border: '1px solid #cbd5e1', background: '#fff', borderRadius: '6px', padding: '7px 11px', cursor: 'pointer', fontWeight: 600 };
const lab: React.CSSProperties = { fontSize: '12px', fontWeight: 600, color: '#475569' }; const select: React.CSSProperties = { display: 'block', width: '100%', marginTop: '4px', padding: '8px', border: '1px solid #cbd5e1', borderRadius: '6px', background: '#fff' }; const th: React.CSSProperties = { textAlign: 'left', padding: '11px', borderBottom: '1px solid #e2e8f0', color: '#64748b' }; const td: React.CSSProperties = { padding: '11px', borderBottom: '1px solid #f1f5f9' }; const banner = (background: string, color: string): React.CSSProperties => ({ display: 'flex', gap: '8px', alignItems: 'center', padding: '10px', marginBottom: '14px', borderRadius: '7px', background, color });
