"""Shared constants for ECLMS.

Only truly cross-cutting constants belong here.  Module-local constants
must stay inside the owning module.
"""

# Module names (must match the module load order documented in EXEC-003).
MODULE_IDENTITY = 'identity'
MODULE_CONTRACTS = 'contracts'
MODULE_WORKFLOW = 'workflow'
MODULE_DOCUMENTS = 'documents'
MODULE_OBLIGATIONS = 'obligations'
MODULE_FINANCES = 'finances'
MODULE_REPORTING = 'reporting'
MODULE_INTELLIGENCE = 'intelligence'
MODULE_AUDIT = 'audit'
MODULE_NOTIFICATIONS = 'notifications'
MODULE_INTEGRATION = 'integration'
MODULE_COMMON = 'common'

MODULES = (
  MODULE_COMMON,
  MODULE_IDENTITY,
  MODULE_CONTRACTS,
  MODULE_WORKFLOW,
  MODULE_DOCUMENTS,
  MODULE_OBLIGATIONS,
  MODULE_FINANCES,
  MODULE_REPORTING,
  MODULE_INTELLIGENCE,
  MODULE_AUDIT,
  MODULE_NOTIFICATIONS,
  MODULE_INTEGRATION,
)

# Contract lifecycle states (MVP scope per EXEC-001).
CONTRACT_STATE_DRAFT = 'DRAFT'
CONTRACT_STATE_SUBMITTED = 'SUBMITTED'
CONTRACT_STATE_UNDER_REVIEW = 'UNDER_REVIEW'
CONTRACT_STATE_APPROVED = 'APPROVED'
CONTRACT_STATE_REJECTED = 'REJECTED'
CONTRACT_STATE_EXECUTED = 'EXECUTED'
CONTRACT_STATE_ACTIVE = 'ACTIVE'
CONTRACT_STATE_AMENDED = 'AMENDED'
CONTRACT_STATE_EXPIRED = 'EXPIRED'
CONTRACT_STATE_TERMINATED = 'TERMINATED'
CONTRACT_STATE_ARCHIVED = 'ARCHIVED'

# API response envelope keys (EXEC-006).
API_VERSION_PREFIX = '/api/v1'
