"""add workflow tables

Revision ID: 53c331530e3d
Revises: b789652b8c89
Create Date: 2026-08-01 22:40:34.972425

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '53c331530e3d'
down_revision: str | Sequence[str] | None = 'b789652b8c89'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_instances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('definition_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_step_number', sa.Integer(), nullable=False),
    sa.Column('started_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='fk_workflow_instances_contract'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_contract_id'), 'workflow_instances', ['contract_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_status'), 'workflow_instances', ['status'], unique=False)
    op.create_table('workflow_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('instance_id', sa.String(length=32), nullable=False),
    sa.Column('from_state', sa.String(length=30), nullable=False),
    sa.Column('to_state', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], name='fk_workflow_history_instance'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_history_created_at'), 'workflow_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_history_instance_id'), 'workflow_history', ['instance_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('instance_id', sa.String(length=32), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('assigned_role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('decided_by', sa.String(length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], name='fk_workflow_steps_instance'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'step_number', name='uq_workflow_steps_instance_step')
    )
    op.create_index(op.f('ix_workflow_steps_instance_id'), 'workflow_steps', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_steps_instance_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_workflow_history_instance_id'), table_name='workflow_history')
    op.drop_index(op.f('ix_workflow_history_created_at'), table_name='workflow_history')
    op.drop_table('workflow_history')
    op.drop_index(op.f('ix_workflow_instances_status'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_contract_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    # ### end Alembic commands ###
