"""add phase 2 workflow fields

Revision ID: a1b2c3d4e5f6
Revises: 53c331530e3d
Create Date: 2026-08-02 10:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: str | Sequence[str] | None = '53c331530e3d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_instances', sa.Column('paused_by', sa.String(length=32), nullable=True))
    op.add_column('workflow_instances', sa.Column('pause_reason', sa.Text(), nullable=True))
    op.add_column('workflow_instances', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_steps', sa.Column('parallel_group_id', sa.String(length=32), nullable=True))
    op.add_column('workflow_steps', sa.Column('condition', sa.String(length=500), nullable=True))
    op.add_column('workflow_steps', sa.Column('timeout_hours', sa.Integer(), nullable=True))
    op.add_column('workflow_steps', sa.Column('escalation_role', sa.String(length=100), nullable=True))
    op.add_column('workflow_steps', sa.Column('delegation_allowed', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('workflow_steps', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_steps', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflow_steps', sa.Column('delegated_to', sa.String(length=32), nullable=True))
    op.add_column('workflow_steps', sa.Column('delegated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_steps', 'delegated_at')
    op.drop_column('workflow_steps', 'delegated_to')
    op.drop_column('workflow_steps', 'escalated_at')
    op.drop_column('workflow_steps', 'started_at')
    op.drop_column('workflow_steps', 'delegation_allowed')
    op.drop_column('workflow_steps', 'escalation_role')
    op.drop_column('workflow_steps', 'timeout_hours')
    op.drop_column('workflow_steps', 'condition')
    op.drop_column('workflow_steps', 'parallel_group_id')
    op.drop_column('workflow_instances', 'paused_at')
    op.drop_column('workflow_instances', 'pause_reason')
    op.drop_column('workflow_instances', 'paused_by')
    # ### end Alembic commands ###
